// src/services/pinnacleService.js

import { pinnacleClient } from '../config/pinnacleClient.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LOCAL_DATA_PATH = path.join(__dirname, '../../data/pinnacle_live.json');
const LOCAL_PREMATCH_DATA_PATH = path.join(__dirname, '../../data/pinnacle_prematch.json');
const DEFAULT_PREMATCH_PRIMARY_HOURS = 6;
const DEFAULT_PREMATCH_PREFETCH_HOURS = 6;
const DEFAULT_PREMATCH_OVERLAP_MINUTES = 30;
const EXCLUDED_MATCH_TERMS = [
    'corners',
    'corner',
    'bookings',
    'booking',
    'cards',
    'card',
    'tarjetas',
    '8 games',
    '8 game'
];

const normalizeMarketText = (value = '') => String(value)
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();

const isExcludedMarketVariant = ({ home = '', away = '', league = '', units = '' } = {}) => {
    if (units && String(units).toLowerCase() !== 'regular') return true;
    const blob = normalizeMarketText(`${home} ${away} ${league} ${units}`);
    return EXCLUDED_MATCH_TERMS.some(term => blob.includes(term));
};

const getPrematchWindowUtc = () => {
    const parsePositive = (value, fallback) => {
        const parsed = Number(value);
        return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
    };

    const nowUtcMs = Date.now();
    const primaryHours = parsePositive(process.env.PREMATCH_WINDOW_PRIMARY_HOURS, DEFAULT_PREMATCH_PRIMARY_HOURS);
    const prefetchHours = parsePositive(process.env.PREMATCH_WINDOW_PREFETCH_HOURS, DEFAULT_PREMATCH_PREFETCH_HOURS);
    const overlapMinutes = parsePositive(process.env.PREMATCH_WINDOW_OVERLAP_MINUTES, DEFAULT_PREMATCH_OVERLAP_MINUTES);
    const totalHours = primaryHours + prefetchHours;

    const startUtcMs = nowUtcMs - (overlapMinutes * 60 * 1000);
    const endUtcMs = nowUtcMs + (totalHours * 60 * 60 * 1000);
    return { nowUtcMs, startUtcMs, endUtcMs, primaryHours, prefetchHours, overlapMinutes };
};

// Conversor de American Odds a Decimal (Pinnacle usa American)
const americanToDecimal = (american) => {
    if (!american) return 0;
    if (american > 0) {
        return (american / 100) + 1;
    } else {
        return (100 / Math.abs(american)) + 1;
    }
};

const parseScoreValue = (value) => {
    if (value === null || value === undefined || value === '') return null;
    const n = Number(value);
    if (!Number.isFinite(n)) return null;
    if (n < 0) return null;
    return Math.floor(n);
};

// HELPER: Calcular Double Chance desde 1x2 (para no depender de la API)
const calculateDCFromMoneyline = (homeStr, drawStr, awayStr) => {
    // Input puede ser string o number
    const h = Number(homeStr);
    const d = Number(drawStr);
    const a = Number(awayStr);
    if (!h || !d || !a) return null;

    // Inversas (Probabilidad Implícita Bruta)
    const probH = 1/h;
    const probD = 1/d;
    const probA = 1/a;
    
    // Sumas para DC
    const dc1X = 1 / (probH + probD);
    const dc12 = 1 / (probH + probA);
    const dcX2 = 1 / (probD + probA);

    return {
        homeDraw: Number(dc1X.toFixed(3)),
        homeAway: Number(dc12.toFixed(3)),
        drawAway: Number(dcX2.toFixed(3))
    };
};

/**
 * STRATEGY: HYBRID FETCHING
 * 1. Global: fetches ALL live markets (20MB+ JSON usually, but filtered by Sport 29 maybe smaller).
 *    Faster for obtaining 1x2 and Totals for MANY matches.
 * 2. Surgical: fetches specific match details (BTTS, Props) using `related` endpoint.
 */

// --------------------------------------------------------------------------------------
// 1. GLOBAL FETCH (THE FIREHOSE) - Usar por defecto en el loop
// --------------------------------------------------------------------------------------
export const getAllPinnacleLiveOdds = async () => {
    // [LOCAL BYPASS] Check if local feed exists (generated by Gateway or Mock)
    if (fs.existsSync(LOCAL_DATA_PATH)) {
        try {
            const fileContent = fs.readFileSync(LOCAL_DATA_PATH, 'utf-8');
            const feed = JSON.parse(fileContent);

            console.log(`   📂 [Pinnacle] Leyendo Feed Local (${feed.count} eventos, act: ${feed.updatedAt})...`);
            
            const oddsMap = new Map();
            
            for (const ev of feed.events) {
                // Normalize participants
                // If mocked, participants exist. If raw Log, maybe not.
                // Assuming Mock structure for now or safe parsing.
                const homePart = ev.participants?.find(p => p.alignment === 'home') || { name: ev.home || "Unknown Home" };
                const awayPart = ev.participants?.find(p => p.alignment === 'away') || { name: ev.away || "Unknown Away" };

                if (isExcludedMarketVariant({
                    home: homePart.name,
                    away: awayPart.name,
                    league: ev.league?.name,
                    units: ev.units
                })) {
                    continue;
                }

                // Build Prices (Soporte Dual: Estructura Plana vs Anidada Legacy)
                let moneyline = null;
                let totals = [];
                
                // CASO A: Estructura Plana (Authenticated API - pinnacleLight.js)
                if (ev.markets && Array.isArray(ev.markets)) {
                    // MONEYLINE
                    const mlMarket = ev.markets.find(m => m.type === 'moneyline' && m.period === 0 && m.status === 'open');
                    if (mlMarket && mlMarket.prices) {
                        const p = {};
                        mlMarket.prices.forEach(pr => {
                            const val = Math.abs(pr.price) > 20 ? americanToDecimal(pr.price) : pr.price;
                            p[pr.designation] = Number(val.toFixed(3));
                        });
                        moneyline = {
                            home: p.home,
                            away: p.away,
                            draw: p.draw || 0,
                            isLive: true
                        };
                    }
                    
                    // TOTALS
                    ev.markets.filter(m => m.type === 'total' && m.period === 0 && m.status === 'open').forEach(m => {
                         const overP = m.prices.find(x => x.designation === 'over');
                         const underP = m.prices.find(x => x.designation === 'under');
                         if (overP && underP) {
                             const valO = Math.abs(overP.price) > 20 ? americanToDecimal(overP.price) : overP.price;
                             const valU = Math.abs(underP.price) > 20 ? americanToDecimal(underP.price) : underP.price;
                             totals.push({
                                 line: overP.points || m.points,
                                 over: Number(valO.toFixed(3)),
                                 under: Number(valU.toFixed(3))
                             });
                         }
                    });

                } else if (ev.prices) { 
                    // CASO B: Estructura Legacy (Mock / Version anterior)
                    const p = {};
                    ev.prices.forEach(pr => {
                        const label = pr.designation.toLowerCase();
                        let val = pr.price;
                        if (Math.abs(val) > 20) {
                             val = americanToDecimal(val); 
                        }
                        p[label] = Number(val.toFixed(3));
                    });

                    if (p.home && p.away) { 
                         moneyline = {
                             home: p.home,
                             away: p.away,
                             draw: p.draw || 0,
                             isLive: true
                         };
                    }
                }

                // [UPDATE] Extract Time & Score for Monitor
                let scoreStr = null;
                let timeStr = "Live";
                
                // A) Score from Participants (Most reliable)
                if (Array.isArray(ev.participants)) {
                    const hP = ev.participants.find(p => p.alignment === 'home');
                    const aP = ev.participants.find(p => p.alignment === 'away');
                    if (hP && aP) {
                        // Sometimes score is inside 'state', sometimes inside 'stats' for periods
                        const hS = parseScoreValue(hP.state?.score ?? (hP.stats?.find(s => s.period === 0)?.score) ?? null);
                        const aS = parseScoreValue(aP.state?.score ?? (aP.stats?.find(s => s.period === 0)?.score) ?? null);
                        if (hS !== null && aS !== null) {
                            scoreStr = `${hS}-${aS}`;
                        }
                    }
                }

                // B) Time from liveStatus or state
                // Pinnacle Arcadia uses 'state' object: { state: 1, minutes: 22 }
                // state: 1 = 1st Half, 2 = HT, 3 = 2nd Half (Approx mapping, needs field test)
                // period status found in 'periods' array
                
                const pState = ev.state || ev.liveStatus;
                
                if (pState) {
                    // Try to determine period
                    let period = pState.period || pState.state; 
                    
                    if (period === 1) timeStr = "1H";
                    else if (period === 2) timeStr = "HT";
                    else if (period === 3) timeStr = "2H";
                    
                    // Clock Calculation
                    let mins = pState.minutes;
                    if (mins !== undefined) {
                        if (period === 3) { // 2nd Half
                            // Pinnacle returns minutes relative to start of period?
                            // Logic: If minutes < 45, likely relative. If > 45, absolute.
                            // However, sample showed "minutes: 20" for a game 85 mins in.
                            // So assume relative.
                            mins = 45 + mins;
                        }
                        timeStr = `${mins}'`;
                    }
                    
                    // Fallback: Check older 'liveStatus.clock' format
                    if (pState.clock && pState.clock.matchTime) {
                        timeStr = `${pState.clock.matchTime}'`;
                    }
                }

                oddsMap.set(ev.id, {
                    id: ev.id, // Exposed for linker
                    match: `${homePart.name} vs ${awayPart.name}`,
                    home: homePart.name,      // [FIX] Needed for Matcher fallbacks
                    away: awayPart.name,      // [FIX] Needed for Matcher fallbacks
                    score: scoreStr,          // [FIX] Now populated
                    time: timeStr,            // [FIX] Now populated
                    date: ev.startTime || ev.date || new Date().toISOString(), // [FIX] Needed for Matcher
                    league: ev.league?.name || "Unknown League",
                    isLive: true,
                    moneyline: moneyline,
                    doubleChance: moneyline ? calculateDCFromMoneyline(moneyline.home, moneyline.draw || 100, moneyline.away) : null,
                    totals: totals // Usamos los totales extraídos
                });
            }
            return oddsMap;
        } catch (e) {
            console.error("❌ Error leyendo Feed Local, cayendo a API Real:", e.message);
        }
    }

    try {
        console.log("   🌐 [Pinnacle] Descargando Snapshot Global (Camaleón API)...");
        const t0 = Date.now();
        
        // Ejecutar Requests en Paralelo
        // Usamos nuestro cliente inteligente que ya devuelve response.data
        const [marketData, matchupData] = await Promise.all([
            // 1. Odds (Global)
            pinnacleClient.get('/sports/29/markets/live/straight', { primaryOnly: false, withSpecials: false, _: Date.now() }),
            // 2. Metadata (Nombres, Score, Tiempo)
            pinnacleClient.get('/sports/29/matchups/live', { brandId: 0, _: Date.now() })
        ]);

        const marketsSafe = marketData || [];
        const matchupsSafe = matchupData || [];

        console.log(`   ✅ Snapshot recibido en ${Date.now() - t0}ms. Procesando ${marketsSafe.length} mercados y ${matchupsSafe.length} partidos...`);
        
        // PASO A: Indexar Metadata (Filtrando solo Units="Regular")
        const metaMap = new Map();
        matchupsSafe.forEach(m => {
            // Solo nos interesan partidos de fútbol regulares (no corners/cards/bookings/8 games)
            if (isExcludedMarketVariant({
                home: m.participants?.find(p => p.alignment === 'home')?.name,
                away: m.participants?.find(p => p.alignment === 'away')?.name,
                league: m.league?.name,
                units: m.units
            })) return;

            // Extraer Score Correcto
            const home = m.participants.find(p => p.alignment === 'home');
            const away = m.participants.find(p => p.alignment === 'away');
            const homeScore = parseScoreValue(home?.state?.score ?? null);
            const awayScore = parseScoreValue(away?.state?.score ?? null);
            
            // Extraer Tiempo
            const stateMap = { 1: '1T', 2: 'HT', 3: '2T' };
            const phase = stateMap[m.state?.state] || (m.liveMode === 'danger_zone' ? 'Live' : '');
            let minutes = m.state?.minutes || 0;

            // [FIX] Corregir tiempo relativo en 2T (Pinnacle a veces manda 15' para el minuto 60)
            if (m.state?.state === 3 && minutes < 45) {
                minutes += 45;
            }

            metaMap.set(m.id, {
                match: `${home?.name} vs ${away?.name}`,
                score: (homeScore !== null && awayScore !== null)
                    ? `${homeScore}-${awayScore}`
                    : null,
                time: `${phase} ${minutes}'`,
                league: m.league?.name,
                isLive: true
            });
        });

        // PASO B: Indexar Cuotas
        const oddsMap = new Map();

        // Procesar array masivo de mercados
        for (const market of marketData) {
            // Ignorar si el matchupId no es de un partido Regular (no está en metaMap)
            // Esto filtra automáticamente cuotas de Corners/Cards que tendrían IDs diferentes
            if (!metaMap.has(market.matchupId)) continue; 

            if (!oddsMap.has(market.matchupId)) {
                oddsMap.set(market.matchupId, {
                    ...metaMap.get(market.matchupId), // Inyectar metadata
                    moneyline: null,
                    doubleChance: null, 
                    totals: []
                });
            }

            const parsed = oddsMap.get(market.matchupId);

            // A) MONEYLINE (1x2)
            if (market.period === 0 && (market.type === 'moneyline' || market.key === 's;0;m')) {
                // [Security Fix] Check if we already have a Moneyline and compare cutoffAt
                // We want the OLDEST cutoffAt (True 1x2), not "Rest of Match"
                const currentCutoff = market.cutoffAt || '9999';
                const existingCutoff = parsed._mlCutoff || '9999';

                // Si ya existe uno y el nuevo es "mas futuro" (mayor cutoff), lo ignoramos (es Rest of Match)
                if (parsed.moneyline && currentCutoff >= existingCutoff) {
                    continue;
                }

                const p = {};
                market.prices.forEach(priceObj => {
                    const dec = americanToDecimal(priceObj.price);
                    if(priceObj.designation) p[priceObj.designation.toLowerCase()] = Number(dec.toFixed(3));
                });
                
                if (p.home && p.away && p.draw) {
                    parsed.moneyline = {
                        home: p.home,
                        away: p.away,
                        draw: p.draw,
                        isLive: true 
                    };
                    parsed._mlCutoff = currentCutoff; // Save for comparison
                    // Auto-Calcular DC
                    parsed.doubleChance = calculateDCFromMoneyline(p.home, p.draw, p.away);
                }
            }

            // B) TOTALS
            if (market.period === 0 && (market.type === 'total' || market.key === 's;0;t')) {
                // Find Over/Under
                const overObj = market.prices.find(x => x.designation === 'over' || x.designation === 'Over');
                const underObj = market.prices.find(x => x.designation === 'under' || x.designation === 'Under');
                
                if (overObj && underObj) {
                     const line = market.points; 
                     parsed.totals.push({
                         line: Number(line),
                         over: Number(americanToDecimal(overObj.price).toFixed(3)),
                         under: Number(americanToDecimal(underObj.price).toFixed(3))
                     });
                }
            }
        }

        return oddsMap;

    } catch (e) {
        console.error("❌ Error en getAllPinnacleLiveOdds (Global):", e.message);
        return new Map();
    }
};

// --------------------------------------------------------------------------------------
// 1.1 PREMATCH CACHE FETCH (CANAL SEPARADO)
// --------------------------------------------------------------------------------------
export const getAllPinnaclePrematchOdds = async () => {
    const mapFromFeed = (events = []) => {
        const oddsMap = new Map();

        for (const ev of events) {
            const homePart = ev.participants?.find(p => p.alignment === 'home') || { name: ev.home || 'Unknown Home' };
            const awayPart = ev.participants?.find(p => p.alignment === 'away') || { name: ev.away || 'Unknown Away' };

            if (isExcludedMarketVariant({
                home: homePart.name,
                away: awayPart.name,
                league: ev.league?.name,
                units: ev.units
            })) {
                continue;
            }

            let moneyline = null;
            const totals = [];

            if (ev.markets && Array.isArray(ev.markets)) {
                const mlMarket = ev.markets.find(m => m.type === 'moneyline' && m.period === 0 && m.status === 'open');
                if (mlMarket?.prices) {
                    const p = {};
                    mlMarket.prices.forEach(pr => {
                        const val = Math.abs(pr.price) > 20 ? americanToDecimal(pr.price) : pr.price;
                        p[pr.designation] = Number(val.toFixed(3));
                    });
                    moneyline = {
                        home: p.home,
                        away: p.away,
                        draw: p.draw || 0,
                        isLive: false
                    };
                }

                ev.markets.filter(m => m.type === 'total' && m.period === 0 && m.status === 'open').forEach(m => {
                    const overP = m.prices?.find(x => x.designation === 'over');
                    const underP = m.prices?.find(x => x.designation === 'under');
                    if (overP && underP) {
                        const valO = Math.abs(overP.price) > 20 ? americanToDecimal(overP.price) : overP.price;
                        const valU = Math.abs(underP.price) > 20 ? americanToDecimal(underP.price) : underP.price;
                        totals.push({
                            line: overP.points || m.points,
                            over: Number(valO.toFixed(3)),
                            under: Number(valU.toFixed(3))
                        });
                    }
                });
            }

            oddsMap.set(ev.id, {
                id: ev.id,
                match: `${homePart.name} vs ${awayPart.name}`,
                home: homePart.name,
                away: awayPart.name,
                score: '0-0',
                time: 'PRE',
                date: ev.startTime || ev.date || new Date().toISOString(),
                league: ev.league?.name || 'Unknown League',
                isLive: false,
                moneyline,
                doubleChance: moneyline ? calculateDCFromMoneyline(moneyline.home, moneyline.draw || 100, moneyline.away) : null,
                totals
            });
        }

        return oddsMap;
    };

    // A) Cache local prematch (preferido)
    if (fs.existsSync(LOCAL_PREMATCH_DATA_PATH)) {
        try {
            const fileContent = fs.readFileSync(LOCAL_PREMATCH_DATA_PATH, 'utf-8');
            const feed = JSON.parse(fileContent);
            const fromLocal = mapFromFeed(feed.events || []);
            if (fromLocal.size > 0) return fromLocal;
        } catch (e) {
            console.warn("⚠️ Error leyendo Feed Local PREMATCH. Fallback a API.", e.message);
        }
    }

    // B) Fallback API (solo si el cache falta o está vacío)
    try {
        console.log('   🌐 [Pinnacle] Fallback PREMATCH via API (cache miss).');
        const [marketData, matchupData] = await Promise.all([
            pinnacleClient.get('/sports/29/markets/straight', { primaryOnly: false, withSpecials: false, _: Date.now() }),
            pinnacleClient.get('/sports/29/matchups', { brandId: 0, _: Date.now() })
        ]);

        const { nowUtcMs, startUtcMs, endUtcMs } = getPrematchWindowUtc();
        const metaMap = new Map();

        (matchupData || []).forEach(m => {
            const startTs = m.startTime ? new Date(m.startTime).getTime() : 0;
            const isLikelyLive = !!m.liveMode || m.state?.minutes !== undefined;

            if (!startTs || startTs < startUtcMs || startTs > endUtcMs) return;
            if (isLikelyLive) return;

            const home = m.participants?.find(p => p.alignment === 'home');
            const away = m.participants?.find(p => p.alignment === 'away');

            if (isExcludedMarketVariant({
                home: home?.name,
                away: away?.name,
                league: m.league?.name,
                units: m.units
            })) return;

            metaMap.set(m.id, {
                id: m.id,
                participants: m.participants,
                home: home?.name || 'Home',
                away: away?.name || 'Away',
                startTime: m.startTime,
                league: m.league,
                units: m.units
            });
        });

        const grouped = new Map();
        (marketData || []).forEach(m => {
            if (!metaMap.has(m.matchupId)) return;
            if (m.period !== 0 || m.status !== 'open') return;

            if (!grouped.has(m.matchupId)) grouped.set(m.matchupId, []);
            grouped.get(m.matchupId).push(m);
        });

        const events = [];
        grouped.forEach((markets, matchupId) => {
            const meta = metaMap.get(matchupId);
            events.push({
                id: matchupId,
                participants: meta.participants,
                startTime: meta.startTime,
                league: meta.league,
                units: meta.units,
                markets
            });
        });

        return mapFromFeed(events);
    } catch (e) {
        console.error('❌ Error fallback API PREMATCH:', e.message);
        return new Map();
    }
};

/**
 * Obtiene las cuotas en vivo de un partido específico desde Pinnacle Arcadia.
 * @param {string|number} pinnacleMatchId - ID del partido en Pinnacle.
 * @returns {Object|null} Objeto con propiedad { home, draw, away, timestamp } o null.
 */
export const getPinnacleLiveOdds = async (pinnacleMatchId) => {
    if (!pinnacleMatchId) return null;
    
    try {
        // Usamos el endpoint que devuelve mercados "straight" (1x2, OU, HC)
        // Usamos pinnacleClient para manejo de identidad y anti-delay
        const data = await pinnacleClient.get(`/matchups/${pinnacleMatchId}/markets/related/straight`);

        // DEBUG: Imprimir raw data para debuggear live status
        // console.log("RAW PINNACLE DATA SAMPLE:", JSON.stringify(data.slice(0, 2), null, 2));


        // ----------------------------------------------------------------
        // 1. MONEYLINE (1x2) & DOUBLE CHANCE
        // ----------------------------------------------------------------
        // Buscamos periodo 0 (Match) o periodo 1/2 si es live (pero para "Full Match 1x2" sigue siendo periodo 0)
        // [Security Fix] Filtramos múltiples mercados para evitar "Rest of Match"
        // El verdadero mercado 1x2 es el que tiene el cutoffAt más antiguo (original).
        
        const allMoneylines = data.filter(m => (m.key === 's;0;m' || m.type === 'moneyline') && m.period === 0 && m.status === 'open');
        
        // Ordenar: Más antiguo primero
        allMoneylines.sort((a, b) => (a.cutoffAt || '9999').localeCompare(b.cutoffAt || '9999'));

        const mlMarket = allMoneylines[0];
        
        // DEBUG: Si hay duplicados, avisar
        if (allMoneylines.length > 1) {
             console.log(`🛡️  Filtered ${allMoneylines.length} ML markets. Selected Cutoff: ${mlMarket.cutoffAt}`);
        }
        
        // --- LIVE CHECK ---
        // Verificamos si hay mercados de periodo 1 o 2, lo cual confirma que es LIVE
        const isLiveConfirmed = data.some(m => m.period === 1 || m.period === 2);

        
        let moneyline = null;
        let doubleChance = null;

        if (mlMarket && mlMarket.prices) {
            const prices = {};
            mlMarket.prices.forEach(p => {
                const decimal = americanToDecimal(p.price);
                if (decimal && p.designation) prices[p.designation.toLowerCase()] = Number(decimal.toFixed(3));
            });

            if (prices.home && prices.away) {
                const draw = prices.draw || 0;
                moneyline = {
                    home: prices.home,
                    away: prices.away,
                    draw: draw,
                    isLive: isLiveConfirmed
                };

                // Calcular Double Chance Real (Fair Probabilities derived from ML)
                // Primero obtenemos probs sin vig del ML
                const invH = 1 / prices.home;
                const invA = 1 / prices.away;
                const invD = draw > 0 ? 1 / draw : 0;
                const totalInv = invH + invA + invD;

                const probH = invH / totalInv;
                const probA = invA / totalInv;
                const probD = invD / totalInv;

                // Probabilidades DC Sumadas
                const prob1X = probH + probD;
                const prob12 = probH + probA;
                const probX2 = probD + probA;

                // Cuotas Fair (Sin Vig) para DC
                doubleChance = {
                    homeDraw: Number((1 / prob1X).toFixed(3)),     // 1X
                    homeAway: Number((1 / prob12).toFixed(3)),     // 12
                    drawAway: Number((1 / probX2).toFixed(3))      // X2
                };
            }
        }

        // ----------------------------------------------------------------
        // 2. TOTALS (Over/Under)
        // ----------------------------------------------------------------
        // Buscamos todos los totales abiertos full match
        const totalMarkets = data.filter(m => m.type === 'total' && m.period === 0 && m.status === 'open');
        let totals = [];
        
        if (totalMarkets.length > 0) {
            totals = totalMarkets.map(m => {
                const overP = m.prices.find(p => p.designation === 'over');
                const underP = m.prices.find(p => p.designation === 'under');
                
                // Algunos formats usan m.points, otros lo tienen en price
                const line = m.points !== undefined ? m.points : (overP?.points);

                if (line !== undefined && overP && underP) {
                    return {
                        line: Number(line),
                        over: Number(americanToDecimal(overP.price).toFixed(3)),
                        under: Number(americanToDecimal(underP.price).toFixed(3))
                    };
                }
                return null;
            }).filter(Boolean);
            
            // Ordenar por diff absoluta con linea "estándar" 2.5 para priorizar
            // o simplemente devolver todos
            totals.sort((a,b) => a.line - b.line);
        }

        return {
            moneyline,
            doubleChance,
            totals,
            timestamp: Date.now()
        };

    } catch (error) {
        // Silenciar errores 404/403 para no ensuciar logs excesivamente
        // console.error(`❌ Error fetching Pinnacle Live Odds (${pinnacleMatchId}):`, error.message);
        return null;
    }
};

/**
 * Calcula la Probabilidad Implícita Real (Fair Chance) removiendo el Vig (Margen).
 * Usa método multiplicativo simple o Power method si se requiere más precisión.
 * @param {number} odd 
 * @param {number} totalImpliedProb - Suma de 1/odd de todas las opciones del mercado
 * @returns {number} Probabilidad en % (0-100)
 */
export const calculateNoVigProb = (odd, totalImpliedProb) => {
    if (!odd || odd <= 1) return 0;
    // Implied Prob raw
    const rawP = 1 / odd;
    // Fair Prob = Raw / Total (Normalización)
    const fairP = rawP / totalImpliedProb;
    return fairP * 100;
};
